
	call getJspItem.bat CasinoAccount
	call getJspItem.bat BetType
	call getJspItem.bat EventType
	call getJspItem.bat CurrencyParam
	call getJspItem.bat LangParam
	call getJspItem.bat Param
	call getJspItem.bat Provider
	call getJspItem.bat Server
	call getJspItem.bat WhlAccount
	call getJspItem.bat WhlAccountCurrencyParam
	call getJspItem.bat WhlAccountLangParam
	call getJspItem.bat WhlAccountParam
	call getJspItem.bat WhiteLabel
	call getJspItem.bat WhlCurrency
	call getJspItem.bat UserGroup
	call getJspItem.bat WalletType
	call getJspItem.bat WhlWalletType
	call getJspItem.bat WhlWalletTypeParam
	call getJspItem.bat WhlCategory
	call getJspItem.bat WhlCategoryParam
	call getJspItem.bat WhlCategoryLangParam
	call getJspItem.bat AuthType
	call getJspItem.bat AuthTypeParam