
	call getJspList.bat CasinoAccount
	call getJspList.bat BetType
	call getJspList.bat EventType
	call getJspList.bat CurrencyParam
	call getJspList.bat LangParam
	call getJspList.bat Param
	call getJspList.bat Provider
	call getJspList.bat Server
	call getJspList.bat WhlAccount
	call getJspList.bat WhlAccountCurrencyParam
	call getJspList.bat WhlAccountLangParam
	call getJspList.bat WhlAccountParam
	call getJspList.bat WhiteLabel
	call getJspList.bat WhlCurrency
	call getJspList.bat UserGroup
	call getJspList.bat WalletType
	call getJspList.bat WhlWalletType
	call getJspList.bat WhlWalletTypeParam
	call getJspList.bat WhlCategory
	call getJspList.bat WhlCategoryParam
	call getJspList.bat WhlCategoryLangParam
	call getJspList.bat AuthType
	call getJspList.bat AuthTypeParam