
	call getModel.bat CasinoAccount
	call getModel.bat BetType
	call getModel.bat EventType
	call getModel.bat CurrencyParam
	call getModel.bat LangParam
	call getModel.bat Param
	call getModel.bat Provider
	call getModel.bat Server
	call getModel.bat WhlAccount
	call getModel.bat WhlAccountCurrencyParam
	call getModel.bat WhlAccountLangParam
	call getModel.bat WhlAccountParam
	call getModel.bat WhiteLabel
	call getModel.bat WhlCurrency
	call getModel.bat UserGroup
	call getModel.bat WalletType
	call getModel.bat WhlWalletType
	call getModel.bat WhlWalletTypeParam
	call getModel.bat WhlCategory
	call getModel.bat WhlCategoryParam
	call getModel.bat WhlCategoryLangParam
	call getModel.bat AuthType
	call getModel.bat AuthTypeParam